version: '2'
services:
  asm:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - ./app:/app
    volumes_from:
      - binaryen
  binaryen:
    build: ../webassembly-v8
    volumes:
      - /usr/local/share/binaryen
